inherit_gem:
  rubocop-ddoherty: 'config/default.yml'

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'test/tmp/**/*'
    - 'spec/tmp/**/*'
    - 'spec/.examples*'
    - 'vendor/bundle/**/*'
