inherit_from: ~/.rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-obsession

AllCops:
  TargetRubyVersion: 3.3
  Include:
    - 'lib/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
#    - 'features/**/*'
  Exclude:
    - 'spec/tmp/**/*'
    - '.simplecov'
    - 'features/**/*'
