inherit_from: ./rubocop-global.yml

AllCops:
  TargetRubyVersion: 3.3
  Include:
    - 'lib/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
#    - 'features/**/*'
  Exclude:
    - 'spec/tmp/**/*'
    - 'spec/.examples.txt'
    - 'bin/setup'
    - '.simplecov'
    - 'features/**/*'
